/*
 * data_flash.c
 *
 *  Created on: Nov 18, 2018
 *      Author: zzr
 */

#include "data_flash.h"

#include "uart_int.h"

void config_dflash(void)
{
	printf("BMHD Size:%u, ADDR:%08X %08X %08X %08X\n",
			sizeof(BMHD_t),
			BMHD_ADDR_0,
			P_BMHD_1,
			P_BMHD_2,
			P_BMHD_3
	);
	flush_stdout();

	printf("BMHD0, STADABM:%08X, BMI:%04X, BMHDID:%04X, CHKSTART:%08X, CHKEND:%08X, CRCRANGE:%08X, nCRCRANGE:%08X, CRCHEAD:%08X, nCRCHEAD:%08X\n",
			(uint32_t)P_BMHD_0->startAddress,
			P_BMHD_0->bmIndex,
			P_BMHD_0->bmhdID,
			P_BMHD_0->chkStart,
			P_BMHD_0->chkEnd,
			P_BMHD_0->crcRange,
			P_BMHD_0->invCrcRange,
			P_BMHD_0->crcHead,
			P_BMHD_0->invCrcHead);
	flush_stdout();

//	printf("MODULE_PMU0.ID\t%08X\t:%08X\n", (uint32_t)&MODULE_PMU0.ID, MODULE_PMU0.ID.U);
//	printf("MODULE_FLASH0.ID\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.ID.U);
	printf("MODULE_FLASH0.ACCEN0\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ACCEN0, MODULE_FLASH0.ACCEN0.U);
//	printf("MODULE_FLASH0.ACCEN1\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ACCEN1, MODULE_FLASH0.ACCEN1.U);
	printf("MODULE_FLASH0.FSR\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.FSR, MODULE_FLASH0.FSR.U);
	printf("MODULE_FLASH0.FCON\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.FCON, MODULE_FLASH0.FCON.U);
	printf("MODULE_FLASH0.CBAB\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.CBAB[0].CFG, MODULE_FLASH0.CBAB[0].CFG.U);
	printf("MODULE_FLASH0.CBAB\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.CBAB[0].STAT, MODULE_FLASH0.CBAB[0].STAT.U);
	printf("MODULE_FLASH0.CBAB\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.CBAB[0].TOP, MODULE_FLASH0.CBAB[0].TOP.U);
	printf("MODULE_FLASH0.COMM0\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.COMM0, MODULE_FLASH0.COMM0.U);
	printf("MODULE_FLASH0.COMM1\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.COMM1, MODULE_FLASH0.COMM1.U);
	printf("MODULE_FLASH0.COMM2\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.COMM2, MODULE_FLASH0.COMM2.U);
	flush_stdout();
	printf("MODULE_FLASH0.FPRO\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.FPRO, MODULE_FLASH0.FPRO.U);
	printf("MODULE_FLASH0.PROCONP\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.PROCONP[0], MODULE_FLASH0.PROCONP[0].U);
	printf("MODULE_FLASH0.PROCOND\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.PROCOND, MODULE_FLASH0.PROCOND.U);
	printf("MODULE_FLASH0.PROCONOTP\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.PROCONOTP[0], MODULE_FLASH0.PROCONOTP[0].U);
	printf("MODULE_FLASH0.PROCONWOP\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.PROCONWOP[0], MODULE_FLASH0.PROCONWOP[0].U);
	printf("MODULE_FLASH0.PROCONDBG\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.PROCONDBG, MODULE_FLASH0.PROCONDBG.U);
	printf("MODULE_FLASH0.PROCONHSMCOTP\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.PROCONHSMCOTP, MODULE_FLASH0.PROCONHSMCOTP.U);
//	printf("MODULE_FLASH0.ECCRD\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.ECCRD.U);
//	printf("MODULE_FLASH0.ECCRP\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.ECCRP[0].U);
//	printf("MODULE_FLASH0.ECCW\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.ECCW.U);
//	printf("MODULE_FLASH0.HSMFCON\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.HSMFCON.U);
//	printf("MODULE_FLASH0.HSMFSR\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.HSMFSR.U);
//	printf("MODULE_FLASH0.HSMMARD\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.HSMMARD.U);
//	printf("MODULE_FLASH0.HSMRRAD\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.HSMRRAD.U);
//	printf("MODULE_FLASH0.HSMRRCT\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.HSMRRCT.U);
//	printf("MODULE_FLASH0.HSMRRD0\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.HSMRRD0.U);
//	printf("MODULE_FLASH0.HSMRRD1\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.HSMRRD1.U);
	flush_stdout();
//	printf("MODULE_FLASH0.MARD\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.MARD.U);
//	printf("MODULE_FLASH0.MARP\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.MARP.U);
//	printf("MODULE_FLASH0.PROCONHSM\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.PROCONHSM.U);
//	printf("MODULE_FLASH0.RDBCFG\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.RDBCFG[0].CFG0.U);
//	flush_stdout();
//	printf("MODULE_FLASH0.RDBCFG\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.RDBCFG[0].CFG1.U);
//	printf("MODULE_FLASH0.RDBCFG\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.RDBCFG[0].CFG2.U);
//	printf("MODULE_FLASH0.RRAD\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.RRAD.U);
//	printf("MODULE_FLASH0.RRCT\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.RRCT.U);
//	printf("MODULE_FLASH0.RRD0\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.RRD0.U);
//	printf("MODULE_FLASH0.RRD1\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.RRD1.U);
//	printf("MODULE_FLASH0.UBAB\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.UBAB[0].CFG.U);
//	printf("MODULE_FLASH0.UBAB\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.UBAB[0].STAT.U);
//	printf("MODULE_FLASH0.UBAB\t%08X\t:%08X\n", (uint32_t)&MODULE_FLASH0.ID, MODULE_FLASH0.UBAB[0].TOP.U);
	flush_stdout();

	extern void __PMU_DFLASH0_BEGIN(void);
	extern void __PMU_DFLASH0_SIZE(void);
	printf("DF0:%08X %08X\n", (uint32_t)__PMU_DFLASH0_BEGIN, (uint32_t)__PMU_DFLASH0_SIZE);
	for(uint32_t i=0; i<0x20/4; ++i)
	{
		printf("%08X ", *((uint32_t*)((uint32_t)__PMU_DFLASH0_BEGIN+i*4)));
	}
	printf("\n");
	flush_stdout();
}

void test_proc_dflash(void)
{

}
