import os

os.chdir('G:/tricore_free_prj/TC234-Test/src')
f=open('bad_practice.inc', mode='w')
header='''/*
 * bad_practice.inc
 *
 *  Created on: May 28, 2019
 *      Author: Administrator
 */
'''
f.write(header)

generate_notification = '//This file is generated by script, do not modify it manually.\n'
f.write(generate_notification)

NOP_REPEAT_N = 4092
nop_repeat_def = '//#define NOP_REPEAT_N %u\n' % NOP_REPEAT_N
f.write(nop_repeat_def)
nop_statement = '_nop();'
for i in range(NOP_REPEAT_N):
    if(0==i%50):
        f.write('\n')
    f.write(nop_statement)
        
f.write('\n\n//Generated content end\n')
f.close()

